# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#"
  weight = 1

[[main]]
  name = "Sobre nosotros"
  url = "/about"
  weight = 10

[[main]]
  name = "Proyectos"
  url = "#projects"
  weight = 20


[[main]]
  name = "Nosotros"
  url = "#people"
  weight = 30

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 40

[[main]]
  name = "Conferencias"
  url = "#talks"
  weight = 50

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
