image: monachus/hugo

before_script:
  - git submodule init
  - git submodule update --force

pages:
  script:
  - hugo --cleanDestinationDir --forceSyncStatic --ignoreCache
  artifacts:
    paths:
    - public
  only:
  - gitlab
