buildDrafts = false
baseurl = "https://mapcolabora.org/"
languageCode = "es"
title = "Mapeado Colaborativo"
theme = "beautifulhugo"

[Params]
  subtitle = "Nuevas cartografías colaborativas al alcance de todos"
  logo = "img/mapeado_colaborativo_logo3b_color.svg"
  #logo = "http://mapcolabora.org/mapeado_colaborativo_logo3b_color.svg"
  favicon = "img/favicon.ico"
  dateFormat = "2/1/2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
 src = "img/cartel-aps.png"
 desc = "Datos de accesibilidad en Zaragoza"
[[Params.bigimg]]
 src = "img/fieldpapers.jpeg"
 desc = "Fieldpapers de la I Mapping Party (2016)"

[Languages]
[Languages.es]
title = "Mapeado Colaborativo"
weight = 1

[Author]
  name = "Mapeado Colaborativo"
  website = "mapcolabora.org"
  email = "mapeadocolaborativo@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "mapcolabora"
  #gitlab = "username"
  twitter = "mapcolabora"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"

[[menu.main]]
    name = "Acerca de"
    url = "page/about/"
    weight = 1

[[menu.main]]
    parent = "Acerca de"
    name = "Sobre Mapeado Colaborativo"
    url = "page/about/"
    weight = 1

[[menu.main]]
    parent = "Acerca de"
    name = "Personas"
    url = "people"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "post"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Proyectos"
    url = "project"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

[[menu.main]]
     identifier = "Contacto & Agenda"
     name = "Contacto & Agenda"
     weight = 20

 [[menu.main]]
     parent = "Contacto & Agenda"
     name = "Lista de Correo"
     weight = 21
     url = "https://groups.google.com/forum/#%21forum/mapeado-colaborativo"

[[menu.main]]
     name = "Meetup"
     parent = "Contacto & Agenda"
     weight = 22
     url = "https://www.meetup.com/es-ES/mapcolabora/"

[[menu.main]]
     name = "Calendario"
     parent = "Contacto & Agenda"
     weight = 23
     url = "page/calendario"
