buildDrafts = false
baseurl = "//mapcolabora.org/"
defaultContentLanguage = "es"
title = "Mapeado Colaborativo"
theme = "beautifulhugo"

[Params]
  logo = "img/mapeado_colaborativo_logo3b_color.svg"
  #logo = "http://mapcolabora.org/mapeado_colaborativo_logo3b_color.svg"
  favicon = "img/favicon.ico"
  dateFormat = "2/1/2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
 src = "img/cartel-aps.png"
 desc = "Datos de accesibilidad en Zaragoza"
[[Params.bigimg]]
 src = "img/fieldpapers.jpeg"
 desc = "Fieldpapers de la I Mapping Party (2016)"
[[Params.bigimg]]
 src = "img/proyectos/ziclabilidad/Ziclabilidad.png"
 desc = "Mapa interactivo sobre la infraestructura ciclista en Zaragoza"

[Author]
 name = "Mapeado Colaborativo"
 website = "mapcolabora.org"
 email = "mapeadocolaborativo@gmail.com"
 #facebook = "username"
 #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
 github = "mapcolabora"
 #gitlab = "username"
 twitter = "mapcolabora"
 #reddit = "username"
 #linkedin = "username"
 #xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"

[Languages]
[Languages.es]
title = "Mapeado Colaborativo"
subtitle = "Nuevas cartografías colaborativas al alcance de todos"
weight = 1
[Languages.en]
title = "Collaborative mapping"
subtitle = "Collaborative cartographies for everyone"
weight = 2

[[Languages.es.menu.main]]
    name = "Acerca de"
    url = "page/about/"
    weight = 1

[[Languages.es.menu.main]]
    parent = "Acerca de"
    name = "Sobre Mapeado Colaborativo"
    url = "page/about/"
    weight = 1

[[Languages.es.menu.main]]
    parent = "Acerca de"
    name = "Personas"
    url = "people"
    weight = 3

[[Languages.es.menu.main]]
    name = "Blog"
    url = "post"
    weight = 2

[[Languages.es.menu.main]]
    identifier = "projects"
    name = "Proyectos"
    url = "project"
    weight = 4

[[Languages.es.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

[[Languages.es.menu.main]]
     identifier = "Contacto & Agenda"
     name = "Contacto & Agenda"
     weight = 20

 [[Languages.es.menu.main]]
     parent = "Contacto & Agenda"
     name = "Lista de Correo"
     weight = 21
     url = "https://groups.google.com/forum/#%21forum/mapeado-colaborativo"

[[Languages.es.menu.main]]
     name = "Meetup"
     parent = "Contacto & Agenda"
     weight = 22
     url = "https://www.meetup.com/es-ES/mapcolabora/"

[[Languages.es.menu.main]]
     name = "Calendario"
     parent = "Contacto & Agenda"
     weight = 23
     url = "page/calendario"

[[Languages.en.menu.main]]
   name = "About us"
   url = "en/page/about/"
   weight = 1
