[build]
  publish = "public"
  command = "hugo --config=config/_default/config.toml"

[context.build]
  HUGO_VERSION = "0.53"

[context.production.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

  [context.deploy-preview.environment]
  HUGO_VERSION = "0.53"
